# Generated by Django 4.1.7 on 2023-03-05 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('name_post', models.CharField(max_length=255)),
                ('text_post', models.TextField()),
                ('category', models.CharField(choices=[('T', 'Танки'), ('H', 'Хилы'), ('DD', 'ДД'), ('Tor', 'Торговцы'), ('G', 'Гилдмастеры'), ('KG', 'Квестгиверы'), ('Kuz', 'Кузнецы'), ('Koz', 'Кожевники'), ('Z', 'Зельевары'), ('M', 'Мастера заклинаний')], max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
                ('one_to_many_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.new')),
                ('one_to_many_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
