# Generated by Django 4.1.7 on 2023-03-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='date_post',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='name_post',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='text_post',
            new_name='text',
        ),
    ]
