# Generated by Django 4.1.7 on 2023-04-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_comment_one_to_many_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='switch',
            field=models.BooleanField(default=False),
        ),
    ]
